services:
  mysql:
    image: mysql:8.4.3-oracle
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet-api
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    # Healthcheck ensures the database is ready before the app starts
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coding-task-container
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: coding-task
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db-data: