spring:
  application.name: coding-task

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:coding-task}?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true #&useTimezone=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  flyway:
    locations: classpath:db/migration,classpath:db/testdata

  jackson:
    deserialization:
      fail-on-unknown-properties: true

  web.resources.add-mappings: false

server:
  port: 8081
